In [1]:
import numpy as np

In [18]:
def n_size_ndarray_creation(n, dtype=np.int):
    X = np.array(range(n**2)).reshape(n,-1)
    return X

In [19]:
n_size_ndarray_creation(4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    if type==0:
        make_matrix = np.zeros(shape,dtype=dtype)
    elif type==1:
        make_matrix = np.ones(shape,dtype=dtype)
    elif type==99:
        make_matrix = np.random.random_sample(shape)
    else:
        make_matrix = np.empty(shape)
    return make_matrix
        
    


In [48]:
zero_or_one_or_empty_ndarray(shape=(2,2),type=1)

array([[1, 1],
       [1, 1]])

In [49]:
zero_or_one_or_empty_ndarray(shape=(2,2),type=99,dtype =np.float64)

array([[0.17716171, 0.0368301 ],
       [0.15731679, 0.81643477]])

In [45]:
make_matrix = np.random.random_sample((5,2))

In [46]:
make_matrix

array([[0.57481104, 0.63696973],
       [0.75631999, 0.42621253],
       [0.10701999, 0.21212424],
       [0.27446441, 0.44027199],
       [0.38667715, 0.06633923]])

In [66]:
def change_shape_of_ndarray(X, n_row):
    if n_row == 1:
        return X.flatten()
    return X.reshape(n_row,-1)

In [54]:
X = np.ones((3,3),dtype=np.int)

In [55]:
change_shape_of_ndarray(X,1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [57]:
change_shape_of_ndarray(X,3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [62]:
type(X.reshape(1,-1))

numpy.ndarray

In [63]:
type(X.flatten())

numpy.ndarray

In [64]:
X.reshape(1,-1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [65]:
X.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [104]:
def concat_ndarray(X_1, X_2, axis_para):
    if X_1.ndim == 1:
        X_1 = X_1.reshape(1, -1)
    if X_2.ndim == 1:
        X_2 = X_2.reshape(1, -1)
    try:
        return np.concatenate((X_1,X_2), axis=axis_para)
    except ValueError as e:
        return False

In [105]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [106]:
concat_ndarray(a,b,0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [107]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [108]:
concat_ndarray(a,b,1)

False

In [138]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    if axis==0:
        X_mean = np.array(X.mean(axis=axis))
        X_var = np.array(X.var(axis=axis))
        Z_val = np.array((X-X_mean)/X_var)
        return Z_val
    elif axis==1:
        means = X.mean(axis=axis).reshape(-1,1)
        std = X.std(axis=axis).reshape(-1,1)
        return (X-means) / std 
    
    elif axis==99:
        X_mean = X.mean(X)
        X_var = X.var(X)
        Z_val = np.array((X-X_mean)/X_var)
        return Z
        

In [139]:
X = np.arange(12,dtype=np.float32).reshape(6,2)
X

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]], dtype=float32)

In [140]:
normalize_ndarray(X,0)

array([[-0.4285714 , -0.4285714 ],
       [-0.25714284, -0.25714284],
       [-0.08571428, -0.08571428],
       [ 0.08571428,  0.08571428],
       [ 0.25714284,  0.25714284],
       [ 0.4285714 ,  0.4285714 ]], dtype=float32)

In [141]:
X_mean = np.array(X.mean(axis=1))
X_mean

array([ 0.5,  2.5,  4.5,  6.5,  8.5, 10.5], dtype=float32)

In [131]:
X_var = np.array(X.var(axis=1))
X_var

array([0.25, 0.25, 0.25, 0.25, 0.25, 0.25], dtype=float32)

In [148]:
X

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]], dtype=float32)

In [149]:
X_mean

array([ 0.5,  2.5,  4.5,  6.5,  8.5, 10.5], dtype=float32)

In [153]:
def save_ndarray(X, filename="test.npy"):
    np.save(filename,X)

In [154]:
save_ndarray(X)

In [164]:
def boolean_index(X, condition):
    return np.where(eval(str("X")+condition))
    

In [156]:
X = np.arange(32,dtype=np.float32).reshape(4,-1)

In [165]:
boolean_index(X,"<4")

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [163]:
np.where(X<3)

(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))

In [166]:
def find_nearest_value(X, target_value):
    pass


In [170]:
target_value = 1

In [182]:
np.argmin(abs(X.reshape(1,-1)-target_value))

array([ 8.,  9., 10., 11., 12., 13., 14., 15.], dtype=float32)

In [188]:
np.argmin(abs(X.reshape(1,-1) - 1))

1

In [194]:
y = X.reshape(1,-1)

In [199]:
y.T[np.argmin(abs(X.reshape(1,-1) - target_value))]

array([1.], dtype=float32)

In [201]:
y.T

array([[ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [11.],
       [12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.],
       [24.],
       [25.],
       [26.],
       [27.],
       [28.],
       [29.],
       [30.],
       [31.]], dtype=float32)

In [275]:
def get_n_largest_values(X, n):
    t= X.flatten()
    return t[np.argsort(t)][n*-1:]

In [276]:
get_n_largest_values(X,5)

array([0.43180843, 0.51330047, 0.67083917, 0.67269018, 0.80319466])

In [271]:
X[X.argmax()]

0.8031946587176806

In [316]:
def get_n_largest_values(X, n):
    return X[X.argsort()[::-1]][:n]

In [317]:
get_n_largest_values(X,5)

array([0.80319466, 0.67269018, 0.67083917, 0.51330047, 0.43180843])

In [308]:
X

array([0.23322212, 0.43180843, 0.21993422, 0.80319466, 0.0823198 ,
       0.67269018, 0.51330047, 0.21434463, 0.67083917, 0.00613475])

In [299]:
X.argsort()

array([9, 4, 7, 2, 0, 1, 6, 8, 5, 3], dtype=int64)

In [302]:
X[X.argsort()][-3:]

array([0.67083917, 0.67269018, 0.80319466])

In [315]:
X[X.argsort()[::-1]]

array([0.80319466, 0.67269018, 0.67083917, 0.51330047, 0.43180843,
       0.23322212, 0.21993422, 0.21434463, 0.0823198 , 0.00613475])

In [304]:
n = 3

In [314]:
X[X.argsort()[::-1]][:n]

array([0.80319466, 0.67269018, 0.67083917])