In [157]:
import numpy as np

In [158]:

class LinearRegression(object):
    def __init__(self, fit_intercept=True, copy_X=True):
        self.fit_intercept = fit_intercept
        self.copy_X = copy_X

        self._coef = None
        self._intercept = None
        self._new_X = None

    def fit(self, X, Y):
        if self.fit_intercept == True:
            make_ones = k = np.ones([X.shape[0],1])
            np.hstack((make_ones,X))
        self._coef = np.dot(np.dot(np.linalg.inv(np.dot(X.T ,X)),X.T),Y)

    def predict(self, X):
        if self.fit_intercept == True:
            make_ones = k = np.ones([X.shape[0],1])
            np.hstack((make_ones,X))
        self._new_X = X
        self._intercept = np.dot(X,self._coef)

    @property
    def coef(self):
        return self._coef

    @property
    def intercept(self):
        return self._intercept

In [159]:
x = LinearRegression(False,True)

In [160]:
tt = np.array([[1,2],[1,4],[1,5]])
tt

array([[1, 2],
       [1, 4],
       [1, 5]])

In [161]:
y = np.array([4,8,12])

In [162]:
x.fit(tt,y)

In [164]:
x.predict(tt)

In [165]:
x.intercept

array([ 3.71428571,  8.85714286, 11.42857143])

In [166]:
np.dot(np.dot(np.linalg.inv(np.dot(tt.T ,tt)),tt.T),y)

array([-1.42857143,  2.57142857])

In [167]:
tt

array([[1, 2],
       [1, 4],
       [1, 5]])

In [168]:
y

array([ 4,  8, 12])

In [169]:
k = np.ones([tt.shape[0],1])

In [170]:
tt,k

(array([[1, 2],
        [1, 4],
        [1, 5]]),
 array([[1.],
        [1.],
        [1.]]))

In [171]:
np.hstack((k,tt))

array([[1., 1., 2.],
       [1., 1., 4.],
       [1., 1., 5.]])